//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _12api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class places
    {
        public int pid { get; set; }
        public int cid { get; set; }
        public string pname { get; set; }
        public string pstreet { get; set; }
        public string city { get; set; }
        public string pdesc { get; set; }
    }
}
