//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _12api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reviews
    {
        public int rid { get; set; }
        public int pid { get; set; }
        public Nullable<int> rating { get; set; }
        public string rdesc { get; set; }
    }
}
